name: Gnosis Protocol DApp

# Whitelisted tokens from Gnosis Contract retrieved from a smart contract
tcr:
  type: 'multi-tcr' # json-file, kleros, multi-tcr, none (for full list, it's not the default)
  config:
    - networkId: 1
      listId: 1
      contractAddress: '0x1854dae560abb0f399d8badca456663ca5c309d0'

    - networkId: 4
      contractAddress: '0xBb840456546496E7640DC09ba9fE06E67C157E1b'

# Gets a price estimation for a given volume
dexPriceEstimator:
  type: 'dex-price-estimator' # dex-price-estimator, the-graph
  config:
    - networkId: 1
      url: https://dex-price-estimator.gnosis.io

    - networkId: 4
      url: https://dex-price-estimator.rinkeby.gnosis.io

# Subgraph abstraction, used for getting the last price
theGraphApi:
  type: 'the-graph' # json-file, kleros, multi-tcr, none (for full list, it's not the default)
  config:
    - networkId: 1
      url: https://api.thegraph.com/subgraphs/name/gnosis/protocol

    - networkId: 4
      url: https://api.thegraph.com/subgraphs/name/gnosis/protocol-rinkeby
